import { Nunito } from "next/font/google";
import "./globals.css";
import StyledComponentsRegistry from './_lib/registry'
import SideBar from "@/components/layout/sideBar";
import ChatBlock from "@/components/chatBlocks";
import MiniNav from "@/components/layout/miniNav";
import { SwitchProvider } from "@/context";
import styles from "./page.module.css"

const inter = Nunito({ subsets: ["latin-ext"] });

export const metadata = {
  title: "Sedboi.euy",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StyledComponentsRegistry>
          <main style={{ display: "flex" }}> 
          <SideBar />
          {children}
          <section className={styles.chat} style={{ display: "flex", flexDirection: "column", paddingTop: "2rem", paddingLeft: "2%", background: "rgb(243 247 247)" }}>
            <MiniNav />
            <SwitchProvider>
              <ChatBlock />
            </SwitchProvider>
          </section>
          </main>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
